export default [
    {
        id: "117030111",
        descricao: "Essencial",
        premio: 144.24,
        coberturas: [
            {
                id: "538437",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 120000,
            },
            {
                id: "538438",
                descricao: "Danos Elétricos",
                valor: 3500,
            },
            {
                id: "538439",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 6000,
            },
            {
                id: "538440",
                descricao: "Responsabilidade Civil Familiar",
                valor: 10000,
            },
            {
                id: "538441",
                descricao: "Assistência Residencial Básica/Simplificada",
                valor: 0,
                premio: 6.37,
            },
            {
                id: "538492",
                descricao: "Sorteio",
                valor: 5000,
                premio: 0,
            },
        ],
    },
    {
        id: "117030112",
        descricao: "Clássica",
        premio: 240.83,
        coberturas: [
            {
                id: "538533",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 250000,
            },
            {
                id: "538534",
                descricao: "Danos Elétricos",
                valor: 5000,
            },
            {
                id: "538535",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 10000,
            },
            {
                id: "538536",
                descricao: "Responsabilidade Civil Familiar",
                valor: 10000,
            },
            {
                id: "538537",
                descricao: "Assistência Residencial Básica/Simplificada",
                valor: 0,
            },
            {
                id: "538542",
                descricao: "Sorteio",
                valor: 5000,
            },
        ],
    },
    {
        id: "117030113",
        descricao: "Superior",
        premio: 376.68,
        coberturas: [
            {
                id: "538588",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 400000,
            },
            {
                id: "538589",
                descricao: "Danos Elétricos",
                valor: 8000,
            },
            {
                id: "538590",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 15000,
            },
            {
                id: "538591",
                descricao: "Responsabilidade Civil Familiar",
                valor: 10000,
            },
            {
                id: "538593",
                descricao: "Sorteio",
                valor: 5000,
            },
            {
                id: "545183",
                descricao: "Assistência Residencial Completa",
                valor: 0,
            },
        ],
    },
    {
        id: "117030114",
        descricao: "Total",
        premio: 582.86,
        coberturas: [
            {
                id: "538588",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 600000,
            },
            {
                id: "538589",
                descricao: "Danos Elétricos",
                valor: 8000,
            },
            {
                id: "538590",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 24000,
            },
            {
                id: "538591",
                descricao: "Responsabilidade Civil Familiar",
                valor: 20000,
            },
            {
                id: "538593",
                descricao: "Sorteio",
                valor: 5000,
            },
            {
                id: "545183",
                descricao: "Assistência Residencial Completa + Eletroassistência com peças",
                valor: 0,
            },
            {
                id: "545183A",
                descricao: "Quebra de vidros, espelhos mármores e granitos",
                valor: 6000,
            },
            {
                id: "545183B",
                descricao: "Equipamentos eletrônicos",
                valor: 3000,
            },
        ],
    },
    {
        id: "117030115",
        descricao: "Master",
        premio: 691.84,
        coberturas: [
            {
                id: "538588",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 750000,
            },
            {
                id: "538589",
                descricao: "Danos Elétricos",
                valor: 8000,
            },
            {
                id: "538590",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 30000,
            },
            {
                id: "538591",
                descricao: "Responsabilidade Civil Familiar",
                valor: 20000,
            },
            {
                id: "538593",
                descricao: "Sorteio",
                valor: 5000,
            },
            {
                id: "545183",
                descricao: "Assistência Residencial Completa + Eletroassistência com peças",
                valor: 0,
            },
            {
                id: "545183A",
                descricao: "Quebra de vidros, espelhos mármores e granitos",
                valor: 7500,
            },
            {
                id: "545183B",
                descricao: "Equipamentos eletrônicos",
                valor: 4000,
            },
        ],
    },
    {
        id: "117030116",
        descricao: "Premium",
        premio: 895.18,
        coberturas: [
            {
                id: "538588",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 1000000,
            },
            {
                id: "538589",
                descricao: "Danos Elétricos",
                valor: 10000,
            },
            {
                id: "538590",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 36000,
            },
            {
                id: "538591",
                descricao: "Responsabilidade Civil Familiar",
                valor: 20000,
            },
            {
                id: "538593",
                descricao: "Sorteio",
                valor: 5000,
            },
            {
                id: "545183",
                descricao: "Assistência Residencial Completa + Eletroassistência com peças",
                valor: 0,
            },
            {
                id: "545183A",
                descricao: "Quebra de vidros, espelhos mármores e granitos",
                valor: 10000,
            },
            {
                id: "545183B",
                descricao: "Equipamentos eletrônicos",
                valor: 5000,
            },
        ],
    },
    {
        id: "117030121",
        descricao: "Essencial",
        premio: 166.32,
        coberturas: [
            {
                id: "538553",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 120000,
                taxa: 0.46992,
                premio: 56.39,
                percentualFranquia: 10,
                valorLimiteFranquiaMinimo: 600,
            },
            {
                id: "538554",
                descricao: "Danos Elétricos",
                valor: 3500,
                taxa: 17.90743,
                premio: 62.68,
                percentualFranquia: 10,
                valorLimiteFranquiaMinimo: 600,
            },
            {
                id: "538555",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 6000,
                taxa: 0.47029,
                premio: 2.82,
            },
            {
                id: "538556",
                descricao: "Responsabilidade Civil Familiar",
                valor: 10000,
                taxa: 0.60719,
                premio: 6.07,
            },
            {
                id: "538557",
                descricao: "Assistência Residencial Básica/Simplificada",
                valor: 0,
                premio: 6.37,
            },
            {
                id: "538562",
                descricao: "Sorteio",
                valor: 5000,
                premio: 0,
            },
            {
                id: "538563",
                descricao: "Roubo e Furto de Bens Mediante Arrombamento",
                valor: 1000,
                taxa: 20.56249,
                premio: 20.56,
            },
        ],
    },
    {
        id: "117030122",
        descricao: "Clássica",
        premio: 296.04,
        coberturas: [
            {
                id: "538564",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 250000,
                taxa: 0.47043,
                premio: 117.61,
                percentualFranquia: 10,
                valorLimiteFranquiaMinimo: 600,
            },
            {
                id: "538565",
                descricao: "Danos Elétricos",
                valor: 5000,
                taxa: 17.9065,
                premio: 89.53,
                percentualFranquia: 10,
                valorLimiteFranquiaMinimo: 600,
            },
            {
                id: "538566",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 10000,
                taxa: 0.47029,
                premio: 4.7,
            },
            {
                id: "538567",
                descricao: "Responsabilidade Civil Familiar",
                valor: 10000,
                taxa: 0.60719,
                premio: 6.07,
            },
            {
                id: "538568",
                descricao: "Assistência Residencial Básica/Simplificada",
                valor: 0,
                premio: 6.37,
            },
            {
                id: "538569",
                descricao: "Sorteio",
                valor: 5000,
                premio: 0,
            },
            {
                id: "538574",
                descricao: "Roubo e Furto de Bens Mediante Arrombamento",
                valor: 2500,
                taxa: 20.56249,
                premio: 51.41,
            },
        ],
    },
    {
        id: "117030123",
        descricao: "Superior",
        premio: 453.96,
        coberturas: [
            {
                id: "538575",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 400000,
                taxa: 0.47011,
                premio: 188.04,
                percentualFranquia: 10,
                valorLimiteFranquiaMinimo: 600,
            },
            {
                id: "538576",
                descricao: "Danos Elétricos",
                valor: 8000,
                taxa: 17.9065,
                premio: 143.25,
                percentualFranquia: 10,
                valorLimiteFranquiaMinimo: 600,
            },
            {
                id: "538577",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 15000,
                taxa: 0.47029,
                premio: 7.05,
            },
            {
                id: "538578",
                descricao: "Responsabilidade Civil Familiar",
                valor: 10000,
                taxa: 0.60719,
                premio: 6.07,
            },
            {
                id: "538584",
                descricao: "Sorteio",
                valor: 5000,
                premio: 0,
            },
            {
                id: "538585",
                descricao: "Roubo e Furto de Bens Mediante Arrombamento",
                valor: 3500,
                taxa: 20.56249,
                premio: 71.97,
            },
            {
                id: "545221",
                descricao: "Assistência Residencial Completa",
                valor: 0,
                premio: 6.37,
            },
        ],
    },
    {
        id: "117030124",
        descricao: "Total",
        premio: 660.86,
        coberturas: [
            {
                id: "538588",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 600000,
            },
            {
                id: "538589",
                descricao: "Danos Elétricos",
                valor: 8000,
            },
            {
                id: "538590",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 24000,
            },
            {
                id: "538591",
                descricao: "Responsabilidade Civil Familiar",
                valor: 20000,
            },
            {
                id: "538593",
                descricao: "Sorteio",
                valor: 5000,
            },
            {
                id: "545183",
                descricao: "Assistência Residencial Completa + Eletroassistência com peças",
                valor: 0,
            },
            {
                id: "545183A",
                descricao: "Quebra de vidros, espelhos mármores e granitos",
                valor: 6000,
            },
            {
                id: "545183B",
                descricao: "Equipamentos eletrônicos",
                valor: 3000,
            },
        ],
    },
    {
        id: "117030125",
        descricao: "Master",
        premio: 800.94,
        coberturas: [
            {
                id: "538588",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 750000,
            },
            {
                id: "538589",
                descricao: "Danos Elétricos",
                valor: 8000,
            },
            {
                id: "538590",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 30000,
            },
            {
                id: "538591",
                descricao: "Responsabilidade Civil Familiar",
                valor: 20000,
            },
            {
                id: "538593",
                descricao: "Sorteio",
                valor: 5000,
            },
            {
                id: "545183",
                descricao: "Assistência Residencial Completa + Eletroassistência com peças",
                valor: 0,
            },
            {
                id: "545183A",
                descricao: "Quebra de vidros, espelhos mármores e granitos",
                valor: 7500,
            },
            {
                id: "545183B",
                descricao: "Equipamentos eletrônicos",
                valor: 4000,
            },
            {
                id: "538585",
                descricao: "Roubo e Furto de Bens Mediante Arrombamento",
                valor: 7000,
            },
            {
                id: "538593",
                descricao: "Sorteio",
                valor: 5000,
            },
        ],
    },
    {
        id: "117030126",
        descricao: "Premium",
        premio: 1051.04,
        coberturas: [
            {
                id: "538588",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 1000000,
            },
            {
                id: "538589",
                descricao: "Danos Elétricos",
                valor: 10000,
            },
            {
                id: "538590",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 36000,
            },
            {
                id: "538591",
                descricao: "Responsabilidade Civil Familiar",
                valor: 20000,
            },
            {
                id: "538593",
                descricao: "Sorteio",
                valor: 5000,
            },
            {
                id: "545183",
                descricao: "Assistência Residencial Completa + Eletroassistência com peças",
                valor: 0,
            },
            {
                id: "545183A",
                descricao: "Quebra de vidros, espelhos mármores e granitos",
                valor: 10000,
            },
            {
                id: "545183B",
                descricao: "Equipamentos eletrônicos",
                valor: 5000,
            },
            {
                id: "538585",
                descricao: "Roubo e Furto de Bens Mediante Arrombamento",
                valor: 10000,
            },
            {
                id: "538593",
                descricao: "Sorteio",
                valor: 5000,
            },
        ],
    },
    {
        id: "117030711",
        descricao: "Essencial",
        premio: 211.93,
        coberturas: [
            {
                id: "538598",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 120000,
                taxa: 0.78376,
                premio: 94.05,
                percentualFranquia: 10,
                valorLimiteFranquiaMinimo: 600,
            },
            {
                id: "538599",
                descricao: "Danos Elétricos",
                valor: 3500,
                taxa: 24.71876,
                premio: 86.52,
                percentualFranquia: 10,
                valorLimiteFranquiaMinimo: 600,
            },
            {
                id: "538600",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 6000,
                taxa: 0.78413,
                premio: 4.7,
            },
            {
                id: "538601",
                descricao: "Responsabilidade Civil Familiar",
                valor: 10000,
                taxa: 0.5718,
                premio: 5.72,
            },
            {
                id: "538602",
                descricao: "Assistência Residencial Básica/Simplificada",
                valor: 0,
                premio: 6.37,
            },
            {
                id: "538603",
                descricao: "Sorteio",
                valor: 5000,
                premio: 0,
            },
        ],
    },
    {
        id: "117030712",
        descricao: "Clássica",
        premio: 364.56,
        coberturas: [
            {
                id: "538608",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 250000,
                taxa: 0.7839,
                premio: 195.98,
                percentualFranquia: 10,
                valorLimiteFranquiaMinimo: 600,
            },
            {
                id: "538609",
                descricao: "Danos Elétricos",
                valor: 5000,
                taxa: 24.71969,
                premio: 123.6,
                percentualFranquia: 10,
                valorLimiteFranquiaMinimo: 600,
            },
            {
                id: "538610",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 10000,
                taxa: 0.78413,
                premio: 7.84,
            },
            {
                id: "538611",
                descricao: "Responsabilidade Civil Familiar",
                valor: 10000,
                taxa: 0.5718,
                premio: 5.72,
            },
            {
                id: "538612",
                descricao: "Assistência Residencial Básica/Simplificada",
                valor: 0,
                premio: 6.37,
            },
            {
                id: "538617",
                descricao: "Sorteio",
                valor: 5000,
                premio: 0,
            },
        ],
    },
    {
        id: "117030713",
        descricao: "Superior",
        premio: 574.56,
        coberturas: [
            {
                id: "538618",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 400000,
                taxa: 0.78369,
                premio: 313.48,
                percentualFranquia: 10,
                valorLimiteFranquiaMinimo: 600,
            },
            {
                id: "538619",
                descricao: "Danos Elétricos",
                valor: 8000,
                taxa: 24.71969,
                premio: 197.76,
                percentualFranquia: 10,
                valorLimiteFranquiaMinimo: 600,
            },
            {
                id: "538620",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 15000,
                taxa: 0.7832,
                premio: 11.75,
            },
            {
                id: "538621",
                descricao: "Responsabilidade Civil Familiar",
                valor: 10000,
                taxa: 0.5718,
                premio: 5.72,
            },
            {
                id: "538623",
                descricao: "Sorteio",
                valor: 5000,
                premio: 0,
            },
            {
                id: "544913",
                descricao: "Assistência Residencial Completa",
                valor: 0,
                premio: 6.37,
            },
        ],
    },
    {
        id: "117030722",
        descricao: "Clássica",
        premio: 525.23,
        coberturas: [
            {
                id: "538639",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 250000,
                taxa: 0.7839,
                premio: 195.98,
                percentualFranquia: 10,
                valorLimiteFranquiaMinimo: 600,
            },
            {
                id: "538640",
                descricao: "Danos Elétricos",
                valor: 5000,
                taxa: 24.71969,
                premio: 123.6,
                percentualFranquia: 10,
                valorLimiteFranquiaMinimo: 600,
            },
            {
                id: "538641",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 10000,
                taxa: 0.78413,
                premio: 7.84,
            },
            {
                id: "538642",
                descricao: "Responsabilidade Civil Familiar",
                valor: 10000,
                taxa: 0.5718,
                premio: 5.72,
            },
            {
                id: "538643",
                descricao: "Assistência Residencial Básica/Simplificada",
                valor: 0,
                premio: 6.37,
            },
            {
                id: "538644",
                descricao: "Sorteio",
                valor: 5000,
                premio: 0,
            },
            {
                id: "538649",
                descricao: "Roubo e Furto de Bens Mediante Arrombamento",
                valor: 2500,
                taxa: 59.85286,
                premio: 149.63,
            },
        ],
    },
    {
        id: "117030723",
        descricao: "Superior",
        premio: 799.68,
        coberturas: [
            {
                id: "538650",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 400000,
                taxa: 0.78369,
                premio: 313.48,
                percentualFranquia: 10,
                valorLimiteFranquiaMinimo: 600,
            },
            {
                id: "538651",
                descricao: "Danos Elétricos",
                valor: 8000,
                taxa: 24.71969,
                premio: 197.76,
                percentualFranquia: 10,
                valorLimiteFranquiaMinimo: 600,
            },
            {
                id: "538652",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 15000,
                taxa: 0.7832,
                premio: 11.75,
            },
            {
                id: "538653",
                descricao: "Responsabilidade Civil Familiar",
                valor: 10000,
                taxa: 0.5718,
                premio: 5.72,
            },
            {
                id: "538659",
                descricao: "Sorteio",
                valor: 5000,
                premio: 0,
            },
            {
                id: "538660",
                descricao: "Roubo e Furto de Bens Mediante Arrombamento",
                valor: 3500,
                taxa: 59.89942,
                premio: 209.65,
            },
            {
                id: "545078",
                descricao: "Assistência Residencial Completa",
                valor: 0,
                premio: 6.37,
            },
        ],
    },
    {
        id: "117030724",
        descricao: "Essencial",
        premio: 276.25,
        coberturas: [
            {
                id: "544904",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 120000,
                taxa: 0.78376,
                premio: 94.05,
                percentualFranquia: 10,
                valorLimiteFranquiaMinimo: 600,
            },
            {
                id: "544905",
                descricao: "Danos Elétricos",
                valor: 3500,
                taxa: 24.71876,
                premio: 86.52,
                percentualFranquia: 10,
                valorLimiteFranquiaMinimo: 600,
            },
            {
                id: "544906",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 6000,
                taxa: 0.78413,
                premio: 4.7,
            },
            {
                id: "544907",
                descricao: "Responsabilidade Civil Familiar",
                valor: 10000,
                taxa: 0.5718,
                premio: 5.72,
            },
            {
                id: "544908",
                descricao: "Roubo e Furto de Bens Mediante Arrombamento",
                valor: 1000,
                taxa: 59.89942,
                premio: 59.9,
            },
            {
                id: "544909",
                descricao: "Assistência Residencial Básica/Simplificada",
                valor: 0,
                premio: 6.37,
            },
            {
                id: "544910",
                descricao: "Sorteio",
                valor: 5000,
                premio: 0,
            },
        ],
    },
    {
        id: "117030714",
        descricao: "Total",
        premio: 852.43,
        coberturas: [
            {
                id: "538588",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 600000,
            },
            {
                id: "538589",
                descricao: "Danos Elétricos",
                valor: 8000,
            },
            {
                id: "538590",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 24000,
            },
            {
                id: "538591",
                descricao: "Responsabilidade Civil Familiar",
                valor: 20000,
            },
            {
                id: "538593",
                descricao: "Sorteio",
                valor: 5000,
            },
            {
                id: "545183",
                descricao: "Assistência Residencial Completa + Eletroassistência com peças",
                valor: 0,
            },
            {
                id: "545183A",
                descricao: "Quebra de vidros, espelhos mármores e granitos",
                valor: 6000,
            },
            {
                id: "545183B",
                descricao: "Equipamentos eletrônicos",
                valor: 3000,
            },
        ],
    },
    {
        id: "117030715",
        descricao: "Master",
        premio: 1016.14,
        coberturas: [
            {
                id: "538588",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 750000,
            },
            {
                id: "538589",
                descricao: "Danos Elétricos",
                valor: 8000,
            },
            {
                id: "538590",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 30000,
            },
            {
                id: "538591",
                descricao: "Responsabilidade Civil Familiar",
                valor: 20000,
            },
            {
                id: "538593",
                descricao: "Sorteio",
                valor: 5000,
            },
            {
                id: "545183",
                descricao: "Assistência Residencial Completa + Eletroassistência com peças",
                valor: 0,
            },
            {
                id: "545183A",
                descricao: "Quebra de vidros, espelhos mármores e granitos",
                valor: 7500,
            },
            {
                id: "545183B",
                descricao: "Equipamentos eletrônicos",
                valor: 4000,
            },
        ],
    },
    {
        id: "117030716",
        descricao: "Premium",
        premio: 1322.25,
        coberturas: [
            {
                id: "538588",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 1000000,
            },
            {
                id: "538589",
                descricao: "Danos Elétricos",
                valor: 10000,
            },
            {
                id: "538590",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 36000,
            },
            {
                id: "538591",
                descricao: "Responsabilidade Civil Familiar",
                valor: 20000,
            },
            {
                id: "538593",
                descricao: "Sorteio",
                valor: 5000,
            },
            {
                id: "545183",
                descricao: "Assistência Residencial Completa + Eletroassistência com peças",
                valor: 0,
            },
            {
                id: "545183A",
                descricao: "Quebra de vidros, espelhos mármores e granitos",
                valor: 10000,
            },
            {
                id: "545183B",
                descricao: "Equipamentos eletrônicos",
                valor: 5000,
            },
        ],
    },
    {
        id: "117030725",
        descricao: "Total",
        premio: 1093.53,
        coberturas: [
            {
                id: '538585',
                descricao: 'Roubo e Furto de Bens Mediante Arrombamento',
                valor: 5000,
            },
            {
                id: "538588",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 600000,
            },
            {
                id: "538589",
                descricao: "Danos Elétricos",
                valor: 8000,
            },
            {
                id: "538590",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 24000,
            },
            {
                id: "538591",
                descricao: "Responsabilidade Civil Familiar",
                valor: 20000,
            },
            {
                id: "538593",
                descricao: "Sorteio",
                valor: 5000,
            },
            {
                id: "545183",
                descricao: "Assistência Residencial Completa + Eletroassistência com peças",
                valor: 0,
            },
            {
                id: "545183A",
                descricao: "Quebra de vidros, espelhos mármores e granitos",
                valor: 6000,
            },
            {
                id: "545183B",
                descricao: "Equipamentos eletrônicos",
                valor: 3000,
            },
        ],
    },
    {
        id: "117030726",
        descricao: "Master",
        premio: 1353.68,
        coberturas: [
            {
                id: '538585',
                descricao: 'Roubo e Furto de Bens Mediante Arrombamento',
                valor: 7000,
            },
            {
                id: "538588",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 750000,
            },
            {
                id: "538589",
                descricao: "Danos Elétricos",
                valor: 8000,
            },
            {
                id: "538590",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 30000,
            },
            {
                id: "538591",
                descricao: "Responsabilidade Civil Familiar",
                valor: 20000,
            },
            {
                id: "538593",
                descricao: "Sorteio",
                valor: 5000,
            },
            {
                id: "545183",
                descricao: "Assistência Residencial Completa + Eletroassistência com peças",
                valor: 0,
            },
            {
                id: "545183A",
                descricao: "Quebra de vidros, espelhos mármores e granitos",
                valor: 7500,
            },
            {
                id: "545183B",
                descricao: "Equipamentos eletrônicos",
                valor: 4000,
            },
        ],
    },
    {
        id: "117030727",
        descricao: "Premium",
        premio: 1804.45,
        coberturas: [
            {
                id: '538585',
                descricao: 'Roubo e Furto de Bens Mediante Arrombamento',
                valor: 10000,
            },
            {
                id: "538588",
                descricao: "Incêndio, Queda de Raio e Explosão de Qualquer Natureza",
                valor: 1000000,
            },
            {
                id: "538589",
                descricao: "Danos Elétricos",
                valor: 10000,
            },
            {
                id: "538590",
                descricao: "Perda ou Pagamento de Aluguel",
                valor: 36000,
            },
            {
                id: "538591",
                descricao: "Responsabilidade Civil Familiar",
                valor: 20000,
            },
            {
                id: "538593",
                descricao: "Sorteio",
                valor: 5000,
            },
            {
                id: "545183",
                descricao: "Assistência Residencial Completa + Eletroassistência com peças",
                valor: 0,
            },
            {
                id: "545183A",
                descricao: "Quebra de vidros, espelhos mármores e granitos",
                valor: 10000,
            },
            {
                id: "545183B",
                descricao: "Equipamentos eletrônicos",
                valor: 5000,
            },
        ],
    },
]
