image: node:12.18.3
pipelines:
  default:
    - step: &tests
        name: Run Tests
        script:
          - test -f ./package-lock.json && echo "Remova o package-lock.json e use o yarn" && exit 1
          - yarn && yarn test
    - step: &syncGithub
        name: Sync with github
        script:
          - git fetch --unshallow || true # para ignorar erros, por exemplo em casos em que a branch nao exista
          - git remote add github git@github.com:AmeDigital/$BITBUCKET_REPO_SLUG.git
          - git pull github $BITBUCKET_BRANCH || true # para ignorar erros, por exemplo em casos em que a branch nao exista
          - git push github $BITBUCKET_BRANCH:$BITBUCKET_BRANCH
          - git push origin $BITBUCKET_BRANCH:$BITBUCKET_BRANCH
  branches:
    '**':
      - step: *syncGithub
    
