export enum Tenants {
    SMARTPHONE = "SMARTPHONE",
    RESIDENTIAL = "RESIDENTIAL",
    PET = "PET",
    LIFE = "LIFE",
    HEALTHCARE = "HEALTHCARE",
    PORTABLE = "PORTABLE",
    RENEW_PORTABLE = "RENEW_PORTABLE",
    FAQ = "FAQ",
    RENEW_PORTABLE_DIGIBEE = "RENEW_PORTABLE_DIGIBEE",
}
