@startuml

title "Processo de listagem de tickets"

actor Miniapp
control API
database DB
control Izio
control BeeLeads
autonumber
Miniapp -> API: getTickets
API -> DB: Busca tickets do usuário
DB -> API: Tickets
API -> Izio: Verificar processadas
note left
Pega cada um dis tickets
e faz uma verificação
na API 1 por 1
buscando a quantidade de games
endnote
Izio -> API: Tickets processados
API -> DB:Salvando qtd games
API -> BeeLeads: Alimentar bilhetes
note left
Os tickets que já possuírem
quantidade de jogadas são 
enviadas para a beeleads
endnote
BeeLeads -> API: OK
API -> Miniapp: Lista de tickets
@enduml